### PR TITLE
Allow usage of Seccomp Profiles on the restricted PSP

### PR DESCRIPTION
**Pull request by fhielpos**
Towards https://github.com/giantswarm/giantswarm/issues/27011

### CODE REVIEW

**Comment by calvix** [comment]
is it properly and fully tested?

**Comment by fhielpos** [comment]
Yes, this doesn't change anything more than allowing workloads to use the profiles, it doesn't set a profile. No impact, has been tested.

**Comment by stone-z** [comment]
Any reason not to make it the same as [the restricted PSP on vintage](https://github.com/giantswarm/k8scloudconfig/blob/v16.2.0/files/k8s-resource/psp_policies.yaml) (e.g. including the default profile)?

**Comment by fiunchinho** [comment]
Should we manually apply this change to already existing CAPI clusters? Upgrading a cluster to this version of `cluster-shared` won't update the PSP's because we are using `ClusterResourceSets` AFAIK

**Comment by primeroz** [comment]
this is also preventing `silence-operator-sync` from `silence-operator 0.9.0` from running

**Comment by primeroz** [comment]
> Should we manually apply this change to already existing CAPI clusters? Upgrading a cluster to this version of cluster-shared won't update the PSP's because we are using ClusterResourceSets AFAIK 

should we keep this open @fhielpos @fiunchinho to track which cluster got it applied ?

**Comment by fhielpos** [comment]
You can manually annotate the restricted PSP too:

```
kubectl annotate psp restricted "seccomp.security.alpha.kubernetes.io/allowedProfileNames='*'"
```

**Comment by fiunchinho** [comment]
> You can manually annotate the restricted PSP too:
> 
> ```
> kubectl annotate psp restricted "seccomp.security.alpha.kubernetes.io/allowedProfileNames='*'"
> ```

Using that command doesn't work
```
$ kubectl annotate psp restricted "seccomp.security.alpha.kubernetes.io/allowedProfileNames='*'"

Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
The PodSecurityPolicy "restricted" is invalid: metadata.annotations[seccomp.security.alpha.kubernetes.io/allowedProfileNames]: Invalid value: "'*'": must be a valid seccomp profile
```

**Pull request merged**
